blocks_args = [
    {
        "num_repeat": 1,
        "kernel_size": 3,
        "stride": [1],
        "expand_ratio": 1,
        "input_filters": 32,
        "output_filters": 16,
        "se_ratio": 0.25,
        "id_skip": True,
    },
    {
        "num_repeat": 2,
        "kernel_size": 3,
        "stride": [2],
        "expand_ratio": 6,
        "input_filters": 16,
        "output_filters": 24,
        "se_ratio": 0.25,
        "id_skip": True,
    },
    {
        "num_repeat": 2,
        "kernel_size": 5,
        "stride": [2],
        "expand_ratio": 6,
        "input_filters": 24,
        "output_filters": 40,
        "se_ratio": 0.25,
        "id_skip": True,
    },
    {
        "num_repeat": 3,
        "kernel_size": 3,
        "stride": [2],
        "expand_ratio": 6,
        "input_filters": 40,
        "output_filters": 80,
        "se_ratio": 0.25,
        "id_skip": True,
    },
    {
        "num_repeat": 3,
        "kernel_size": 5,
        "stride": [1],
        "expand_ratio": 6,
        "input_filters": 80,
        "output_filters": 112,
        "se_ratio": 0.25,
        "id_skip": True,
    },
    {
        "num_repeat": 4,
        "kernel_size": 5,
        "stride": [2],
        "expand_ratio": 6,
        "input_filters": 112,
        "output_filters": 192,
        "se_ratio": 0.25,
        "id_skip": True,
    },
    {
        "num_repeat": 1,
        "kernel_size": 3,
        "stride": [1],
        "expand_ratio": 6,
        "input_filters": 192,
        "output_filters": 320,
        "se_ratio": 0.25,
        "id_skip": True,
    },
]

global_params = {
    "width_coefficient": 1.0,
    "depth_coefficient": 1.0,
    "image_size": 224,
    "dropout_rate": 0.2,
    "num_classes": 1000,
    "batch_norm_momentum": 0.99,
    "batch_norm_epsilon": 0.001,
    "drop_connect_rate": 0.2,
    "depth_divisor": 8,
    "min_depth": None,
    "include_top": True,
}
